osx_image: xcode8.3
language: objective-c
script:
- set -o pipefail && xcodebuild build test -workspace Gridicons.xcworkspace -scheme GridiconsDemo -sdk iphonesimulator  -destination "name=iPhone 7" ONLY_ACTIVE_ARCH=NO | xcpretty -c
